export interface RouteMetadata {
  path: string;
  label: string;
  description?: string;
  keywords?: string[];
  category?: string;
  deprecated?: boolean;
}

export const routes: Record<string, RouteMetadata> = {
  home: {
    path: '/',
    label: 'Home',
    description: 'TIME AI platform homepage',
    keywords: ['home', 'main', 'landing'],
    category: 'general',
  },
  search: {
    path: '/search',
    label: 'Search',
    description: 'Unified omnibox-style search with direct navigation',
    keywords: ['search', 'find', 'navigate', 'omnibox'],
    category: 'general',
  },
  browserSearch: {
    path: '/browser-search',
    label: 'Browser Search',
    description: 'Backward-compatible redirect to unified search',
    keywords: ['search', 'browser', 'redirect'],
    category: 'general',
  },
  worldsFirst: {
    path: '/worlds-first',
    label: "World's First",
    description: "50 World's First innovations in AI governance and workflow orchestration",
    keywords: ['innovations', 'first', 'features', 'unique'],
    category: 'features',
  },
  agentRegistry: {
    path: '/agent-registry',
    label: 'Agent Registry',
    description: 'Comprehensive catalog of AI agents with verification status',
    keywords: ['agents', 'registry', 'catalog', 'verification'],
    category: 'agents',
  },
  agentPassports: {
    path: '/agent-passports',
    label: 'Agent Passports',
    description: 'Agent credentials and verification data with metrics dashboard',
    keywords: ['passports', 'credentials', 'verification', 'agents'],
    category: 'agents',
  },
  aiNotary: {
    path: '/ai-notary',
    label: 'AI Notary',
    description: 'Notarize and verify documents with blockchain-backed proof',
    keywords: ['notary', 'verification', 'documents', 'blockchain'],
    category: 'governance',
  },
  recommendedAdditions: {
    path: '/recommended-additions',
    label: 'Recommended Additions',
    description: 'Platform additions catalog with roadmap builder',
    keywords: ['additions', 'roadmap', 'features', 'planning'],
    category: 'operations',
  },
  integrationRollout: {
    path: '/integration-rollout',
    label: 'Integration Rollout',
    description: 'Strategic integration steps with deliverables and DoD checklists',
    keywords: ['integration', 'rollout', 'deployment', 'planning'],
    category: 'infrastructure',
  },
  nextUpgrade: {
    path: '/next-upgrade',
    label: 'Next Upgrade',
    description: 'Upgrade theme planner with localStorage persistence',
    keywords: ['upgrade', 'planning', 'themes', 'roadmap'],
    category: 'operations',
  },
  aiTaxAssistance: {
    path: '/ai-tax-assistance',
    label: 'AI Tax Assistance',
    description: 'Comprehensive tax filing guidance with IRS resources',
    keywords: ['tax', 'assistance', 'filing', 'irs'],
    category: 'operations',
  },
  markets: {
    path: '/markets',
    label: 'Markets',
    description: 'Real TIME and TRAV token prices with market information',
    keywords: ['markets', 'prices', 'tokens', 'trading'],
    category: 'tokens',
  },
  rewardsIncentives: {
    path: '/rewards-incentives',
    label: '🎁 Rewards & Staking',
    description: 'User rewards system with point balance and activity tracking',
    keywords: ['rewards', 'incentives', 'points', 'activity', 'staking'],
    category: 'tokens',
  },
  marketplace: {
    path: '/marketplace',
    label: 'Marketplace',
    description: 'Digital marketplace with backend-driven items',
    keywords: ['marketplace', 'items', 'purchase', 'unlock'],
    category: 'marketplace',
  },
  marketplaceDetail: {
    path: '/marketplace/$itemId',
    label: 'Marketplace Item',
    description: 'Detailed view of marketplace item with unlock functionality',
    keywords: ['marketplace', 'item', 'detail', 'unlock'],
    category: 'marketplace',
  },
  agentMarketplace: {
    path: '/marketplace/agent',
    label: 'Agent Marketplace',
    description: '',
    keywords: ['marketplace', 'agent'],
    category: 'marketplace',
  },
  workflowMarketplace: {
    path: '/marketplace/workflow',
    label: 'Workflow Marketplace',
    description: '',
    keywords: ['marketplace', 'workflow'],
    category: 'marketplace',
  },
  integrationMarketplace: {
    path: '/marketplace/integration',
    label: 'Integration Marketplace',
    description: '',
    keywords: ['marketplace', 'integration'],
    category: 'marketplace',
  },
  monetization: {
    path: '/marketplace/monetization',
    label: 'Monetization',
    description: '',
    keywords: ['marketplace', 'monetization'],
    category: 'marketplace',
  },
  workflowPackMarketplace: {
    path: '/workflow-pack-marketplace',
    label: 'Workflow Pack Marketplace',
    description: 'Browse and filter workflow packs with search and category filters',
    keywords: ['workflow', 'packs', 'marketplace', 'search'],
    category: 'workflows',
  },
  partnerIntegration: {
    path: '/partner-integration',
    label: 'Partner Integration',
    description: 'Partner integration layer with API credential management',
    keywords: ['partner', 'integration', 'api', 'credentials'],
    category: 'infrastructure',
  },
  partnerIntegrationLayer: {
    path: '/partner-integration-layer',
    label: 'Partner Integration Layer',
    description: 'Blank page for partner integration layer',
    keywords: ['partner', 'integration', 'layer'],
    category: 'infrastructure',
  },
  globalRailsIntegration: {
    path: '/global-rails-integration',
    label: 'Global Rails Integration',
    description: 'Comprehensive payment rails integration documentation',
    keywords: ['rails', 'payment', 'integration', 'swift', 'fednow'],
    category: 'infrastructure',
  },
  apiKeys: {
    path: '/api-keys',
    label: 'API Keys',
    description: 'Blank page for API keys management',
    keywords: ['api', 'keys', 'management'],
    category: 'infrastructure',
  },
  apiDocumentation: {
    path: '/api-documentation',
    label: 'API Documentation',
    description: 'Blank page for API documentation',
    keywords: ['api', 'documentation', 'reference'],
    category: 'infrastructure',
  },
  connectionStatus: {
    path: '/connection-status',
    label: 'Connection Status',
    description: 'Blank page for connection status monitoring',
    keywords: ['connection', 'status', 'monitoring'],
    category: 'infrastructure',
  },
  webhooks: {
    path: '/webhooks',
    label: 'Webhooks',
    description: 'Blank page for webhooks management',
    keywords: ['webhooks', 'integration', 'events'],
    category: 'infrastructure',
  },
  integrationMarketplaceOld: {
    path: '/integration-marketplace',
    label: 'Integration Marketplace (Old)',
    description: 'Blank page for integration marketplace',
    keywords: ['integration', 'marketplace'],
    category: 'infrastructure',
  },
  aiTalk: {
    path: '/community/ai-talk',
    label: 'AI Talk',
    description: 'Community discussion topics with robust loading states',
    keywords: ['community', 'discussion', 'topics', 'talk'],
    category: 'community',
  },
  topicDetail: {
    path: '/community/topic/$topicId',
    label: 'Topic Detail',
    description: 'Detailed view of community topic with replies',
    keywords: ['topic', 'detail', 'replies', 'discussion'],
    category: 'community',
  },
  communityNews: {
    path: '/community/news',
    label: 'Community News',
    description: 'Static news page with always-visible content',
    keywords: ['news', 'community', 'updates'],
    category: 'community',
  },
  communityHub: {
    path: '/community',
    label: 'Community Hub',
    description: 'Community hub landing page with navigation cards',
    keywords: ['community', 'hub', 'landing'],
    category: 'community',
  },
  tradeMarket: {
    path: '/trade/market',
    label: 'Trade Market',
    description: 'Blank page for trade market',
    keywords: ['trade', 'market'],
    category: 'trade',
  },
  buyTokens: {
    path: '/trade/buy',
    label: 'Buy Tokens',
    description: 'Blank page for buying tokens',
    keywords: ['buy', 'tokens', 'purchase'],
    category: 'trade',
  },
  sellTokens: {
    path: '/trade/sell',
    label: 'Sell Tokens',
    description: 'Blank page for selling tokens',
    keywords: ['sell', 'tokens'],
    category: 'trade',
  },
  convert: {
    path: '/trade/convert',
    label: 'Convert',
    description: 'Blank page for token conversion',
    keywords: ['convert', 'tokens', 'exchange'],
    category: 'trade',
  },
  history: {
    path: '/trade/history',
    label: 'Order History',
    description: 'Blank page for order history',
    keywords: ['history', 'orders', 'transactions'],
    category: 'trade',
  },
  openOrders: {
    path: '/trade/open-orders',
    label: 'Open Orders',
    description: 'Blank page for open orders',
    keywords: ['orders', 'open', 'pending'],
    category: 'trade',
  },
  executionHistory: {
    path: '/workflow-management/execution-history',
    label: 'Execution History',
    description: 'Blank page for workflow execution history',
    keywords: ['workflow', 'execution', 'history'],
    category: 'workflows',
  },
  scheduledWorkflows: {
    path: '/workflow-management/scheduled-workflows',
    label: 'Scheduled Workflows',
    description: 'Blank page for scheduled workflows',
    keywords: ['workflow', 'scheduled', 'automation'],
    category: 'workflows',
  },
  workflowPacks: {
    path: '/workflow-packs',
    label: 'Workflow Packs',
    description: 'Blank page for workflow packs',
    keywords: ['workflow', 'packs'],
    category: 'workflows',
  },
  workflowBuilder: {
    path: '/workflow-builder',
    label: 'Workflow Builder',
    description: 'Blank page for workflow builder',
    keywords: ['workflow', 'builder', 'create'],
    category: 'workflows',
  },
  industryKits: {
    path: '/industry-kits',
    label: 'Industry Kits',
    description: 'Blank page for industry kits',
    keywords: ['industry', 'kits', 'templates'],
    category: 'workflows',
  },
  testingSandbox: {
    path: '/testing-sandbox',
    label: 'Testing Sandbox',
    description: 'Blank page for testing sandbox',
    keywords: ['testing', 'sandbox', 'development'],
    category: 'workflows',
  },
  policyEngine: {
    path: '/policy-engine',
    label: 'Policy Engine',
    description: 'Blank page for policy engine',
    keywords: ['policy', 'engine', 'governance'],
    category: 'governance',
  },
  versionControl: {
    path: '/version-control',
    label: 'Version Control',
    description: 'Blank page for version control',
    keywords: ['version', 'control', 'history'],
    category: 'governance',
  },
  complianceReports: {
    path: '/compliance-reports',
    label: 'Compliance Reports',
    description: 'Blank page for compliance reports',
    keywords: ['compliance', 'reports', 'audit'],
    category: 'governance',
  },
  policyConflicts: {
    path: '/policy-conflicts',
    label: 'Policy Conflicts',
    description: 'Blank page for policy conflicts',
    keywords: ['policy', 'conflicts', 'resolution'],
    category: 'governance',
  },
  auditLogs: {
    path: '/audit-logs',
    label: 'Audit Logs',
    description: 'Blank page for audit logs',
    keywords: ['audit', 'logs', 'history'],
    category: 'governance',
  },
  rolePermissions: {
    path: '/role-permissions',
    label: 'Role Permissions',
    description: 'Blank page for role permissions',
    keywords: ['role', 'permissions', 'access'],
    category: 'governance',
  },
  solutionsOverview: {
    path: '/solutions/overview',
    label: 'Solutions Overview',
    description: 'Blank page for solutions overview',
    keywords: ['solutions', 'overview'],
    category: 'solutions',
  },
  solutionsFunctionsUseCases: {
    path: '/solutions/functions-use-cases',
    label: 'Solutions Functions & Use Cases',
    description: 'Combined TIME AI and TRAV AI functions and use cases',
    keywords: ['solutions', 'functions', 'use cases', 'time ai', 'trav ai'],
    category: 'solutions',
  },
  solutionsWorldsFirst: {
    path: '/solutions/worlds-first',
    label: "Solutions World's First",
    description: 'Blank page for solutions world\'s first',
    keywords: ['solutions', 'worlds first'],
    category: 'solutions',
  },
  solutionsCommodities: {
    path: '/solutions/commodities',
    label: 'Solutions Commodities',
    description: 'Blank page for solutions commodities',
    keywords: ['solutions', 'commodities'],
    category: 'solutions',
  },
  solutionsCaseStudies: {
    path: '/solutions/case-studies',
    label: 'Solutions Case Studies',
    description: 'Blank page for solutions case studies',
    keywords: ['solutions', 'case studies'],
    category: 'solutions',
  },
  solutionsProblemSolver: {
    path: '/solutions/problem-solver',
    label: 'Solutions Problem Solver',
    description: 'Blank page for solutions problem solver',
    keywords: ['solutions', 'problem solver'],
    category: 'solutions',
  },
  platformAdditions: {
    path: '/operations/platform-additions',
    label: 'Platform Additions',
    description: 'Blank page for platform additions',
    keywords: ['platform', 'additions'],
    category: 'operations',
  },
  operationsNextUpgrade: {
    path: '/operations/next-upgrade',
    label: 'Next Upgrade',
    description: 'Blank page for next upgrade',
    keywords: ['upgrade', 'next'],
    category: 'operations',
  },
  operationsAITaxAssistance: {
    path: '/operations/ai-tax-assistance',
    label: 'AI Tax Assistance',
    description: 'Comprehensive tax filing guidance',
    keywords: ['tax', 'assistance', 'filing'],
    category: 'operations',
  },
  operationsEnterpriseOnboarding: {
    path: '/operations/enterprise-onboarding',
    label: 'Enterprise Onboarding',
    description: 'Blank page for enterprise onboarding',
    keywords: ['enterprise', 'onboarding'],
    category: 'operations',
  },
  rwaDashboard: {
    path: '/operations/rwa-dashboard',
    label: 'RWA Dashboard',
    description: 'Blank page for RWA dashboard',
    keywords: ['rwa', 'dashboard'],
    category: 'operations',
  },
  systemStatus: {
    path: '/operations/system-status',
    label: 'System Status',
    description: 'Blank page for system status',
    keywords: ['system', 'status'],
    category: 'operations',
  },
  userManagement: {
    path: '/operations/user-management',
    label: 'User Management',
    description: 'Blank page for user management',
    keywords: ['user', 'management'],
    category: 'operations',
  },
  resourcesNews: {
    path: '/resources/news',
    label: 'News',
    description: 'Blank page for news',
    keywords: ['news', 'resources'],
    category: 'resources',
  },
  resourcesDocumentation: {
    path: '/resources/documentation',
    label: 'Documentation',
    description: 'Blank page for documentation',
    keywords: ['documentation', 'resources'],
    category: 'resources',
  },
  resourcesTraining: {
    path: '/resources/training',
    label: 'Training',
    description: 'Blank page for training',
    keywords: ['training', 'resources'],
    category: 'resources',
  },
  resourcesPartners: {
    path: '/resources/partners',
    label: 'Partners',
    description: 'Blank page for partners',
    keywords: ['partners', 'resources'],
    category: 'resources',
  },
  resourcesSupport: {
    path: '/resources/support',
    label: 'Support',
    description: 'Blank page for support',
    keywords: ['support', 'resources'],
    category: 'resources',
  },
  tokenomics: {
    path: '/tokens/tokenomics',
    label: 'Tokenomics',
    description: 'Blank page for tokenomics',
    keywords: ['tokenomics', 'tokens'],
    category: 'tokens',
  },
  wallet: {
    path: '/tokens/wallet',
    label: 'Wallet',
    description: 'Blank page for wallet',
    keywords: ['wallet', 'tokens'],
    category: 'tokens',
  },
  marketData: {
    path: '/tokens/market-data',
    label: 'Market Data',
    description: 'Blank page for market data',
    keywords: ['market', 'data', 'tokens'],
    category: 'tokens',
  },
  transactions: {
    path: '/tokens/transactions',
    label: 'Transactions',
    description: 'Blank page for transactions',
    keywords: ['transactions', 'tokens'],
    category: 'tokens',
  },
  rewardsStaking: {
    path: '/tokens/rewards-staking',
    label: 'Rewards & Staking',
    description: 'Blank page for rewards and staking',
    keywords: ['rewards', 'staking', 'tokens'],
    category: 'tokens',
  },
  analytics: {
    path: '/tokens/analytics',
    label: 'Analytics',
    description: 'Blank page for analytics',
    keywords: ['analytics', 'tokens'],
    category: 'tokens',
  },
  whaleTracking: {
    path: '/tokens/whale-tracking',
    label: 'Whale Tracking',
    description: 'Blank page for whale tracking',
    keywords: ['whale', 'tracking', 'tokens'],
    category: 'tokens',
  },
  tokenGovernance: {
    path: '/tokens/governance',
    label: 'Token Governance',
    description: 'Blank page for token governance',
    keywords: ['governance', 'tokens'],
    category: 'tokens',
  },
  solutions: {
    path: '/solutions',
    label: 'Solutions Catalog',
    description: 'Comprehensive solutions catalog with search and filtering',
    keywords: ['solutions', 'catalog', 'search'],
    category: 'solutions',
  },
  commodities: {
    path: '/dashboards/commodities',
    label: 'Commodities Dashboard',
    description: 'Commodities dashboard with simulated metrics',
    keywords: ['commodities', 'dashboard', 'rwa'],
    category: 'dashboards',
  },
  rwa: {
    path: '/dashboards/rwa',
    label: 'RWA Dashboard',
    description: 'Real-world assets dashboard with conceptual vaults',
    keywords: ['rwa', 'dashboard', 'assets'],
    category: 'dashboards',
  },
  timeAIFunctionsUseCases: {
    path: '/time-ai/functions-use-cases',
    label: 'TIME AI Functions & Use Cases',
    description: 'Enterprise workflow orchestration capabilities and use cases',
    keywords: ['time ai', 'functions', 'use cases', 'enterprise'],
    category: 'features',
  },
  timeAITokenomics: {
    path: '/time-ai/tokenomics',
    label: 'TIME AI Tokenomics',
    description: 'Enterprise governance token distribution and economics',
    keywords: ['time ai', 'tokenomics', 'governance', 'token'],
    category: 'tokens',
  },
  travAIFunctionsUseCases: {
    path: '/trav-ai/functions-use-cases',
    label: 'TRAV AI Functions & Use Cases',
    description: 'Personal AI companion features and lifestyle use cases',
    keywords: ['trav ai', 'functions', 'use cases', 'personal'],
    category: 'features',
  },
  travAITokenomics: {
    path: '/trav-ai/tokenomics',
    label: 'TRAV AI Tokenomics',
    description: 'Reward token distribution and earning mechanisms',
    keywords: ['trav ai', 'tokenomics', 'rewards', 'token'],
    category: 'tokens',
  },
  evidenceComplianceMap: {
    path: '/time-ai/evidence-compliance-map',
    label: 'Evidence & Compliance Map',
    description: 'Workflow evidence tracking with compliance framework mapping',
    keywords: ['evidence', 'compliance', 'audit', 'framework'],
    category: 'governance',
  },
  agentCapabilityProofGenerator: {
    path: '/agent-capability-proof-generator',
    label: 'Agent Capability Proof Generator',
    description: 'Generate and verify cryptographically signed agent capability proofs',
    keywords: ['agent', 'capability', 'proof', 'verification'],
    category: 'agents',
  },
  valueDashboard: {
    path: '/value-dashboard',
    label: 'Value Dashboard',
    description: 'Key performance metrics and KPIs for TIME AI',
    keywords: ['value', 'dashboard', 'metrics', 'kpi'],
    category: 'dashboards',
  },
  controlledFanOutDemo: {
    path: '/controlled-fan-out-demo',
    label: 'Controlled Fan-Out Demo',
    description: 'Interactive demo of controlled fan-out pattern with live metrics',
    keywords: ['fan-out', 'demo', 'concurrency', 'tasks'],
    category: 'demos',
  },
  controlledFanInDemo: {
    path: '/controlled-fan-in-demo',
    label: 'Controlled Fan-In Demo',
    description: 'Interactive demo of controlled fan-in pattern with predictable latency',
    keywords: ['fan-in', 'demo', 'concurrency', 'channels'],
    category: 'demos',
  },
  roadmap: {
    path: '/roadmap',
    label: 'Roadmap',
    description: 'Personal roadmap with user-selected platform additions',
    keywords: ['roadmap', 'planning', 'additions'],
    category: 'operations',
  },
  enterpriseOnboarding: {
    path: '/enterprise-onboarding',
    label: 'Enterprise Onboarding',
    description: 'Enterprise onboarding and deployment request management',
    keywords: ['enterprise', 'onboarding', 'deployment'],
    category: 'operations',
  },
  timeAIGlobalRailsMapping: {
    path: '/time-ai/global-rails-mapping',
    label: 'TIME AI Global Rails Integration',
    description: 'Step-by-step mapping of TIME AI governance across payment rails',
    keywords: ['time ai', 'rails', 'integration', 'payment'],
    category: 'infrastructure',
  },
  designYourAIAgent: {
    path: '/trav-ai/design-your-ai-agent',
    label: 'Design Your AI Agent',
    description: 'Blank page for designing AI agents',
    keywords: ['design', 'agent', 'trav ai'],
    category: 'agents',
  },
  simulationSandbox: {
    path: '/trav-ai/simulation-sandbox',
    label: 'Simulation Sandbox',
    description: 'Blank page for simulation sandbox',
    keywords: ['simulation', 'sandbox', 'trav ai'],
    category: 'testing',
  },
  trainingModules: {
    path: '/trav-ai/training-modules',
    label: 'Training Modules',
    description: 'Blank page for training modules',
    keywords: ['training', 'modules', 'trav ai'],
    category: 'training',
  },
  driftPrediction: {
    path: '/trav-ai/drift-prediction',
    label: 'Drift Prediction',
    description: 'Blank page for drift prediction',
    keywords: ['drift', 'prediction', 'trav ai'],
    category: 'monitoring',
  },
  cognitiveTelemetry: {
    path: '/trav-ai/cognitive-telemetry',
    label: 'Cognitive Telemetry',
    description: 'Blank page for cognitive telemetry',
    keywords: ['cognitive', 'telemetry', 'trav ai'],
    category: 'monitoring',
  },
  agentTemplates: {
    path: '/timeai/agent-templates',
    label: 'Agent Templates',
    description: 'Blank page for agent templates',
    keywords: ['agent', 'templates', 'time ai'],
    category: 'agents',
  },
  agentHealthMonitor: {
    path: '/timeai/agent-health-monitor',
    label: 'Agent Health Monitor',
    description: 'Blank page for agent health monitoring',
    keywords: ['agent', 'health', 'monitor', 'time ai'],
    category: 'monitoring',
  },
  agentActivityFeed: {
    path: '/timeai/agent-activity-feed',
    label: 'Agent Activity Feed',
    description: 'Blank page for agent activity feed',
    keywords: ['agent', 'activity', 'feed', 'time ai'],
    category: 'monitoring',
  },
  riskDashboard: {
    path: '/timeai/risk-dashboard',
    label: 'Risk Dashboard',
    description: 'Blank page for risk dashboard',
    keywords: ['risk', 'dashboard', 'time ai'],
    category: 'monitoring',
  },
  agentSettings: {
    path: '/timeai/agent-settings',
    label: 'Agent Settings',
    description: 'Blank page for agent settings',
    keywords: ['agent', 'settings', 'time ai'],
    category: 'settings',
  },
};
