import { LucideIcon, Package, Mail, Plane, Router, Cpu, Zap, Globe, Network, Server, Cloud, Database, Shield, Truck, Box, Building2, Factory, Rocket, DollarSign, Coins, Landmark, Wallet, Link, Users, TrendingUp, Briefcase, Building, ShoppingCart, Home, Store, CreditCard, Banknote, Send, MessageSquare, BarChart3, Camera, Image, PieChart, Video, MessageCircle, Phone, ShieldCheck, Bitcoin, CircleDollarSign, TrendingDown, Smartphone, Wifi, Code } from 'lucide-react';

export interface SolutionEntry {
  id: string;
  title: string;
  icon: LucideIcon;
  description: string;
  path: string;
  category: 'Logistics' | 'Technology' | 'Semiconductors' | 'Finance' | 'Payments' | 'Enterprise Software' | 'Cloud Infrastructure' | 'Data & Analytics' | 'AI & Machine Learning' | 'Blockchain' | 'Social Media' | 'Communication' | 'Security' | 'Retail' | 'Government' | 'Stablecoins' | 'Developer Tools';
  searchKeywords: string[];
}

export const solutionsCatalog: SolutionEntry[] = [
  // Logistics
  {
    id: 'fedex',
    title: 'FedEx',
    icon: Package,
    description: 'Customs delays, network optimization, and delivery solutions',
    path: '/solutions/fedex',
    category: 'Logistics',
    searchKeywords: ['fedex', 'shipping', 'customs', 'delivery', 'express', 'ground'],
  },
  {
    id: 'ups',
    title: 'UPS',
    icon: Package,
    description: 'Delivery optimization, routing efficiency, and cost reduction',
    path: '/solutions/ups',
    category: 'Logistics',
    searchKeywords: ['ups', 'shipping', 'delivery', 'routing', 'logistics'],
  },
  {
    id: 'usps',
    title: 'USPS',
    icon: Mail,
    description: 'Processing bottlenecks, tracking, and delivery improvements',
    path: '/solutions/usps',
    category: 'Logistics',
    searchKeywords: ['usps', 'postal', 'mail', 'delivery', 'tracking'],
  },
  {
    id: 'dhl',
    title: 'DHL',
    icon: Plane,
    description: 'International shipping, customs compliance, and routing',
    path: '/solutions/dhl',
    category: 'Logistics',
    searchKeywords: ['dhl', 'international', 'shipping', 'customs', 'express'],
  },
  {
    id: 'amazon',
    title: 'Amazon Logistics',
    icon: Box,
    description: 'Last-mile delivery optimization and fulfillment center efficiency',
    path: '/solutions/amazon',
    category: 'Logistics',
    searchKeywords: ['amazon', 'logistics', 'fulfillment', 'last mile', 'delivery', 'aws'],
  },
  // Retail
  {
    id: 'shoprite',
    title: 'ShopRite',
    icon: ShoppingCart,
    description: 'Grocery supply chain optimization and inventory management',
    path: '/solutions/shoprite',
    category: 'Retail',
    searchKeywords: ['shoprite', 'grocery', 'retail', 'supermarket', 'supply chain'],
  },
  {
    id: 'stop-and-shop',
    title: 'Stop & Shop',
    icon: ShoppingCart,
    description: 'Retail operations, fresh food logistics, and customer experience',
    path: '/solutions/stop-and-shop',
    category: 'Retail',
    searchKeywords: ['stop and shop', 'grocery', 'retail', 'supermarket'],
  },
  {
    id: 'lowes',
    title: "Lowe's",
    icon: Home,
    description: 'Home improvement supply chain and store operations optimization',
    path: '/solutions/lowes',
    category: 'Retail',
    searchKeywords: ['lowes', 'home improvement', 'retail', 'hardware', 'construction'],
  },
  {
    id: 'home-depot',
    title: 'The Home Depot',
    icon: Home,
    description: 'Building materials logistics and contractor service coordination',
    path: '/solutions/home-depot',
    category: 'Retail',
    searchKeywords: ['home depot', 'hardware', 'construction', 'retail', 'building'],
  },
  {
    id: 'walmart',
    title: 'Walmart',
    icon: Store,
    description: 'Retail supply chain at scale and omnichannel fulfillment',
    path: '/solutions/walmart',
    category: 'Retail',
    searchKeywords: ['walmart', 'retail', 'supply chain', 'grocery', 'ecommerce'],
  },
  {
    id: 'costco',
    title: 'Costco',
    icon: Store,
    description: 'Warehouse club operations and bulk inventory management',
    path: '/solutions/costco',
    category: 'Retail',
    searchKeywords: ['costco', 'warehouse', 'wholesale', 'bulk', 'membership'],
  },
  {
    id: 'sams-club',
    title: "Sam's Club",
    icon: Store,
    description: 'Membership warehouse optimization and business services',
    path: '/solutions/sams-club',
    category: 'Retail',
    searchKeywords: ['sams club', 'warehouse', 'wholesale', 'membership', 'walmart'],
  },
  // Semiconductors
  {
    id: 'nvidia',
    title: 'NVIDIA',
    icon: Cpu,
    description: 'Leading AI compute infrastructure with GPU optimization challenges',
    path: '/solutions/nvidia',
    category: 'Semiconductors',
    searchKeywords: ['nvidia', 'gpu', 'ai', 'cuda', 'graphics'],
  },
  {
    id: 'tsmc',
    title: 'TSMC',
    icon: Factory,
    description: 'Critical semiconductor manufacturing with yield optimization needs',
    path: '/solutions/tsmc',
    category: 'Semiconductors',
    searchKeywords: ['tsmc', 'semiconductor', 'chip', 'manufacturing'],
  },
  {
    id: 'samsung',
    title: 'Samsung',
    icon: Smartphone,
    description: 'Diverse product portfolio requiring unified supply chain management',
    path: '/solutions/samsung',
    category: 'Semiconductors',
    searchKeywords: ['samsung', 'electronics', 'mobile', 'semiconductor'],
  },
  {
    id: 'intel',
    title: 'Intel',
    icon: Cpu,
    description: 'Legacy architecture modernization and competitive positioning',
    path: '/solutions/intel',
    category: 'Semiconductors',
    searchKeywords: ['intel', 'processor', 'chip', 'semiconductor'],
  },
  {
    id: 'amd',
    title: 'AMD',
    icon: Cpu,
    description: 'Rapid growth requiring scalable infrastructure and supply chain',
    path: '/solutions/amd',
    category: 'Semiconductors',
    searchKeywords: ['amd', 'processor', 'gpu', 'ryzen', 'radeon'],
  },
  // Cloud Infrastructure
  {
    id: 'cisco',
    title: 'Cisco',
    icon: Router,
    description: 'Network security, configuration, and monitoring solutions',
    path: '/solutions/cisco',
    category: 'Cloud Infrastructure',
    searchKeywords: ['cisco', 'network', 'security', 'routing', 'infrastructure'],
  },
  {
    id: 'microsoft',
    title: 'Microsoft',
    icon: Building2,
    description: 'Cloud infrastructure, Azure optimization, and enterprise solutions',
    path: '/solutions/microsoft',
    category: 'Cloud Infrastructure',
    searchKeywords: ['microsoft', 'azure', 'cloud', 'enterprise', 'windows'],
  },
  {
    id: 'google',
    title: 'Google Cloud',
    icon: Cloud,
    description: 'GCP optimization, infrastructure scaling, and cost management',
    path: '/solutions/google',
    category: 'Cloud Infrastructure',
    searchKeywords: ['google', 'gcp', 'cloud', 'infrastructure', 'kubernetes'],
  },
  {
    id: 'aws',
    title: 'AWS',
    icon: Server,
    description: 'Amazon Web Services optimization, architecture, and security',
    path: '/solutions/aws',
    category: 'Cloud Infrastructure',
    searchKeywords: ['aws', 'amazon', 'cloud', 'ec2', 's3', 'lambda'],
  },
  {
    id: 'oracle',
    title: 'Oracle',
    icon: Database,
    description: 'Database optimization, performance tuning, and migration',
    path: '/solutions/oracle',
    category: 'Cloud Infrastructure',
    searchKeywords: ['oracle', 'database', 'sql', 'performance', 'enterprise'],
  },
  {
    id: 'cloudflare',
    title: 'Cloudflare',
    icon: Cloud,
    description: 'Edge computing and security at internet scale',
    path: '/solutions/cloudflare',
    category: 'Cloud Infrastructure',
    searchKeywords: ['cloudflare', 'cdn', 'security', 'ddos'],
  },
  {
    id: 'vercel',
    title: 'Vercel',
    icon: Globe,
    description: 'Edge deployment platform with developer experience optimization',
    path: '/solutions/vercel',
    category: 'Developer Tools',
    searchKeywords: ['vercel', 'nextjs', 'deployment', 'frontend', 'edge'],
  },
  {
    id: 'netlify',
    title: 'Netlify',
    icon: Globe,
    description: 'Jamstack platform with build optimization and edge functions',
    path: '/solutions/netlify',
    category: 'Developer Tools',
    searchKeywords: ['netlify', 'jamstack', 'deployment', 'cdn'],
  },
  // Technology (General)
  {
    id: 'ibm',
    title: 'IBM',
    icon: Server,
    description: 'Enterprise computing, mainframe optimization, and hybrid cloud',
    path: '/solutions/ibm',
    category: 'Technology',
    searchKeywords: ['ibm', 'mainframe', 'enterprise', 'cloud', 'watson'],
  },
  {
    id: 'ge',
    title: 'GE',
    icon: Factory,
    description: 'Industrial IoT, predictive maintenance, and operational efficiency',
    path: '/solutions/ge',
    category: 'Technology',
    searchKeywords: ['ge', 'general electric', 'industrial', 'iot', 'manufacturing'],
  },
  {
    id: 'panasonic',
    title: 'Panasonic',
    icon: Cpu,
    description: 'Supply chain optimization and manufacturing automation',
    path: '/solutions/panasonic',
    category: 'Technology',
    searchKeywords: ['panasonic', 'electronics', 'manufacturing', 'supply chain'],
  },
  {
    id: 'apple',
    title: 'Apple',
    icon: Cpu,
    description: 'Ecosystem integration, supply chain, and device optimization',
    path: '/solutions/apple',
    category: 'Technology',
    searchKeywords: ['apple', 'ios', 'iphone', 'mac', 'ecosystem'],
  },
  {
    id: 'duckduckgo',
    title: 'DuckDuckGo',
    icon: Globe,
    description: 'Privacy-focused search, data protection, and user anonymity',
    path: '/solutions/duckduckgo',
    category: 'Technology',
    searchKeywords: ['duckduckgo', 'search', 'privacy', 'browser'],
  },
  {
    id: 'github',
    title: 'GitHub',
    icon: Code,
    description: 'Code collaboration platform with CI/CD and security scanning at scale',
    path: '/solutions/github',
    category: 'Developer Tools',
    searchKeywords: ['github', 'git', 'code', 'repository', 'devops'],
  },
  // Data & Analytics
  {
    id: 'snowflake',
    title: 'Snowflake',
    icon: Database,
    description: 'Cloud data platform with cost optimization and performance tuning',
    path: '/solutions/snowflake',
    category: 'Data & Analytics',
    searchKeywords: ['snowflake', 'data warehouse', 'cloud', 'analytics'],
  },
  {
    id: 'databricks',
    title: 'Databricks',
    icon: TrendingUp,
    description: 'Unified analytics platform with lakehouse architecture challenges',
    path: '/solutions/databricks',
    category: 'Data & Analytics',
    searchKeywords: ['databricks', 'spark', 'data', 'analytics', 'ml'],
  },
  {
    id: 'supabase',
    title: 'Supabase',
    icon: Database,
    description: 'Open-source Firebase alternative with Postgres scaling challenges',
    path: '/solutions/supabase',
    category: 'Data & Analytics',
    searchKeywords: ['supabase', 'database', 'postgres', 'backend'],
  },
  {
    id: 'mongodb',
    title: 'MongoDB',
    icon: Database,
    description: 'Document database with sharding and performance optimization needs',
    path: '/solutions/mongodb',
    category: 'Data & Analytics',
    searchKeywords: ['mongodb', 'database', 'nosql', 'atlas'],
  },
  {
    id: 'redis',
    title: 'Redis',
    icon: Server,
    description: 'In-memory data store with persistence and clustering requirements',
    path: '/solutions/redis',
    category: 'Data & Analytics',
    searchKeywords: ['redis', 'cache', 'database', 'in-memory'],
  },
  // Enterprise Software
  {
    id: 'sap',
    title: 'SAP',
    icon: Building2,
    description: 'Enterprise resource planning with cloud migration complexity',
    path: '/solutions/sap',
    category: 'Enterprise Software',
    searchKeywords: ['sap', 'erp', 'enterprise', 'business'],
  },
  {
    id: 'salesforce',
    title: 'Salesforce',
    icon: Cloud,
    description: 'CRM platform with AI integration and data management needs',
    path: '/solutions/salesforce',
    category: 'Enterprise Software',
    searchKeywords: ['salesforce', 'crm', 'cloud', 'sales'],
  },
  {
    id: 'servicenow',
    title: 'ServiceNow',
    icon: Building2,
    description: 'Enterprise workflow automation with AI-driven optimization',
    path: '/solutions/servicenow',
    category: 'Enterprise Software',
    searchKeywords: ['servicenow', 'itsm', 'workflow', 'automation'],
  },
  {
    id: 'palantir',
    title: 'Palantir',
    icon: Shield,
    description: 'Enterprise data integration with complex security requirements',
    path: '/solutions/palantir',
    category: 'Enterprise Software',
    searchKeywords: ['palantir', 'data', 'analytics', 'government', 'enterprise'],
  },
  // AI & Machine Learning
  {
    id: 'openai',
    title: 'OpenAI',
    icon: Zap,
    description: 'AI model optimization, API efficiency, and cost management',
    path: '/solutions/openai',
    category: 'AI & Machine Learning',
    searchKeywords: ['openai', 'gpt', 'chatgpt', 'ai', 'machine learning'],
  },
  {
    id: 'anthropic',
    title: 'Anthropic',
    icon: Zap,
    description: 'AI safety research with constitutional AI and scaling challenges',
    path: '/solutions/anthropic',
    category: 'AI & Machine Learning',
    searchKeywords: ['anthropic', 'claude', 'ai', 'llm', 'safety'],
  },
  {
    id: 'caffeine-ai',
    title: 'Caffeine AI',
    icon: Zap,
    description: 'Workflow governance and agent management solutions',
    path: '/solutions/caffeine-ai',
    category: 'AI & Machine Learning',
    searchKeywords: ['caffeine ai', 'workflow', 'governance'],
  },
  {
    id: 'grok',
    title: 'Grok',
    icon: Zap,
    description: 'Real-time information access and conversational AI',
    path: '/solutions/grok',
    category: 'AI & Machine Learning',
    searchKeywords: ['grok', 'ai', 'real-time', 'conversational'],
  },
  // Blockchain
  {
    id: 'icp',
    title: 'ICP',
    icon: Network,
    description: 'Internet Computer Protocol optimization and architecture',
    path: '/solutions/icp',
    category: 'Blockchain',
    searchKeywords: ['icp', 'internet computer', 'blockchain'],
  },
  {
    id: 'dfinity',
    title: 'DFINITY',
    icon: Network,
    description: 'Developer onboarding and best practices',
    path: '/solutions/dfinity',
    category: 'Blockchain',
    searchKeywords: ['dfinity', 'developer', 'architecture'],
  },
  {
    id: 'ethereum',
    title: 'Ethereum',
    icon: Bitcoin,
    description: 'Gas fees, smart contract security, and Layer 2 scaling',
    path: '/solutions/ethereum',
    category: 'Blockchain',
    searchKeywords: ['ethereum', 'eth', 'smart contract', 'defi'],
  },
  {
    id: 'solana',
    title: 'Solana',
    icon: Network,
    description: 'Network congestion and program deployment optimization',
    path: '/solutions/solana',
    category: 'Blockchain',
    searchKeywords: ['solana', 'sol', 'blockchain', 'rust'],
  },
  {
    id: 'polygon',
    title: 'Polygon',
    icon: Network,
    description: 'Bridge security and cross-chain synchronization',
    path: '/solutions/polygon',
    category: 'Blockchain',
    searchKeywords: ['polygon', 'matic', 'layer 2', 'scaling'],
  },
  {
    id: 'avalanche',
    title: 'Avalanche',
    icon: Network,
    description: 'Subnet architecture with institutional blockchain deployment needs',
    path: '/solutions/avalanche',
    category: 'Blockchain',
    searchKeywords: ['avalanche', 'avax', 'blockchain', 'subnet', 'defi'],
  },
  {
    id: 'cardano',
    title: 'Cardano',
    icon: Network,
    description: 'Research-driven blockchain with formal verification requirements',
    path: '/solutions/cardano',
    category: 'Blockchain',
    searchKeywords: ['cardano', 'ada', 'blockchain', 'proof of stake'],
  },
  {
    id: 'tezos',
    title: 'Tezos',
    icon: Network,
    description: 'Self-amending blockchain with on-chain governance complexity',
    path: '/solutions/tezos',
    category: 'Blockchain',
    searchKeywords: ['tezos', 'xtz', 'blockchain', 'governance'],
  },
  {
    id: 'base',
    title: 'Base',
    icon: Network,
    description: 'Layer 2 transaction throughput and bridge security',
    path: '/solutions/base',
    category: 'Blockchain',
    searchKeywords: ['base', 'layer 2', 'coinbase', 'ethereum'],
  },
  {
    id: 'gemini',
    title: 'Gemini',
    icon: Bitcoin,
    description: 'Regulated crypto exchange and custody solutions',
    path: '/solutions/gemini',
    category: 'Blockchain',
    searchKeywords: ['gemini', 'exchange', 'crypto', 'custody'],
  },
  // Stablecoins
  {
    id: 'usdc',
    title: 'USDC',
    icon: CircleDollarSign,
    description: 'USD reserve backing and multi-chain deployment',
    path: '/solutions/usdc',
    category: 'Stablecoins',
    searchKeywords: ['usdc', 'stablecoin', 'circle', 'usd'],
  },
  {
    id: 'usdt',
    title: 'USDT',
    icon: CircleDollarSign,
    description: 'Multi-blockchain deployment and reserve transparency',
    path: '/solutions/usdt',
    category: 'Stablecoins',
    searchKeywords: ['usdt', 'tether', 'stablecoin', 'usd'],
  },
  {
    id: 'usd1',
    title: 'USD1',
    icon: CircleDollarSign,
    description: 'Stablecoin market differentiation and regulatory compliance',
    path: '/solutions/usd1',
    category: 'Stablecoins',
    searchKeywords: ['usd1', 'stablecoin', 'regulated'],
  },
  {
    id: 'wlfi',
    title: 'WLFI',
    icon: CircleDollarSign,
    description: 'DeFi platform infrastructure and regulatory compliance',
    path: '/solutions/wlfi',
    category: 'Stablecoins',
    searchKeywords: ['wlfi', 'defi', 'stablecoin'],
  },
  // Finance
  {
    id: 'copper',
    title: 'Copper',
    icon: Banknote,
    description: 'Digital banking infrastructure and financial services optimization',
    path: '/solutions/copper',
    category: 'Finance',
    searchKeywords: ['copper', 'banking', 'fintech', 'digital banking'],
  },
  {
    id: 'fidelity',
    title: 'Fidelity',
    icon: TrendingUp,
    description: 'Portfolio management and retirement planning optimization',
    path: '/solutions/fidelity',
    category: 'Finance',
    searchKeywords: ['fidelity', 'investment', 'retirement', 'portfolio'],
  },
  {
    id: 'robinhood',
    title: 'Robinhood',
    icon: TrendingUp,
    description: 'Commission-free trading and crypto integration',
    path: '/solutions/robinhood',
    category: 'Finance',
    searchKeywords: ['robinhood', 'trading', 'stocks', 'crypto'],
  },
  {
    id: 'tradingview',
    title: 'TradingView',
    icon: BarChart3,
    description: 'Market data aggregation and charting performance',
    path: '/solutions/tradingview',
    category: 'Finance',
    searchKeywords: ['tradingview', 'charts', 'trading', 'analysis'],
  },
  {
    id: 'coingecko',
    title: 'CoinGecko',
    icon: Bitcoin,
    description: 'Crypto market data aggregation and price accuracy',
    path: '/solutions/coingecko',
    category: 'Finance',
    searchKeywords: ['coingecko', 'crypto', 'market data', 'prices'],
  },
  {
    id: 'nyse',
    title: 'NYSE',
    icon: TrendingUp,
    description: 'High-frequency trading infrastructure and market data distribution',
    path: '/solutions/nyse',
    category: 'Finance',
    searchKeywords: ['nyse', 'stock exchange', 'trading', 'market'],
  },
  {
    id: 'swift',
    title: 'SWIFT',
    icon: Send,
    description: 'International payment messaging and settlement delays',
    path: '/solutions/swift',
    category: 'Finance',
    searchKeywords: ['swift', 'international', 'payment', 'banking'],
  },
  {
    id: 'fednow',
    title: 'FedNow',
    icon: Send,
    description: 'Real-time payment settlement and bank integration',
    path: '/solutions/fednow',
    category: 'Finance',
    searchKeywords: ['fednow', 'payment', 'real-time', 'federal reserve'],
  },
  // Payments
  {
    id: 'visa',
    title: 'Visa',
    icon: CreditCard,
    description: 'Global payment network with real-time fraud detection requirements',
    path: '/solutions/visa',
    category: 'Payments',
    searchKeywords: ['visa', 'payment', 'card', 'transaction'],
  },
  {
    id: 'mastercard',
    title: 'Mastercard',
    icon: CreditCard,
    description: 'Payment processing at scale with emerging crypto integration',
    path: '/solutions/mastercard',
    category: 'Payments',
    searchKeywords: ['mastercard', 'payment', 'card', 'transaction'],
  },
  {
    id: 'stripe',
    title: 'Stripe',
    icon: CreditCard,
    description: 'Developer-first payment platform with global expansion challenges',
    path: '/solutions/stripe',
    category: 'Payments',
    searchKeywords: ['stripe', 'payment', 'api', 'fintech'],
  },
  {
    id: 'zelle',
    title: 'Zelle',
    icon: Send,
    description: 'Peer-to-peer payments and instant transfer optimization',
    path: '/solutions/zelle',
    category: 'Payments',
    searchKeywords: ['zelle', 'payment', 'transfer', 'p2p', 'banking'],
  },
  {
    id: 'paypal',
    title: 'PayPal',
    icon: CreditCard,
    description: 'Digital payments, fraud prevention, and global transactions',
    path: '/solutions/paypal',
    category: 'Payments',
    searchKeywords: ['paypal', 'payment', 'ecommerce', 'digital wallet'],
  },
  {
    id: 'venmo',
    title: 'Venmo',
    icon: Send,
    description: 'Social payment feed privacy and instant transfer',
    path: '/solutions/venmo',
    category: 'Payments',
    searchKeywords: ['venmo', 'payment', 'social', 'p2p'],
  },
  // Social Media
  {
    id: 'x-twitter',
    title: 'X (Twitter)',
    icon: MessageSquare,
    description: 'Real-time content delivery and content moderation',
    path: '/solutions/x-twitter',
    category: 'Social Media',
    searchKeywords: ['x', 'twitter', 'social media', 'microblogging'],
  },
  {
    id: 'snapchat',
    title: 'Snapchat',
    icon: Camera,
    description: 'Ephemeral content delivery and AR features',
    path: '/solutions/snapchat',
    category: 'Social Media',
    searchKeywords: ['snapchat', 'social media', 'ar', 'ephemeral'],
  },
  {
    id: 'instagram',
    title: 'Instagram',
    icon: Image,
    description: 'Photo/video storage and content recommendation',
    path: '/solutions/instagram',
    category: 'Social Media',
    searchKeywords: ['instagram', 'social media', 'photos', 'meta'],
  },
  {
    id: 'truth-social',
    title: 'Truth Social',
    icon: MessageSquare,
    description: 'Platform infrastructure scaling and content moderation',
    path: '/solutions/truth-social',
    category: 'Social Media',
    searchKeywords: ['truth social', 'social media', 'platform'],
  },
  {
    id: 'yahoo',
    title: 'Yahoo',
    icon: Globe,
    description: 'Content delivery, ad optimization, and platform scaling',
    path: '/solutions/yahoo',
    category: 'Social Media',
    searchKeywords: ['yahoo', 'media', 'advertising', 'content'],
  },
  {
    id: 'meta',
    title: 'Meta',
    icon: Network,
    description: 'Social platform optimization, content moderation, and infrastructure',
    path: '/solutions/meta',
    category: 'Social Media',
    searchKeywords: ['meta', 'facebook', 'instagram', 'social media'],
  },
  {
    id: 'youtube',
    title: 'YouTube',
    icon: Video,
    description: 'Video streaming, content delivery, and creator monetization',
    path: '/solutions/youtube',
    category: 'Social Media',
    searchKeywords: ['youtube', 'video', 'streaming', 'content', 'google'],
  },
  // Communication
  {
    id: 'zoom',
    title: 'Zoom',
    icon: Video,
    description: 'Video conferencing infrastructure and quality optimization',
    path: '/solutions/zoom',
    category: 'Communication',
    searchKeywords: ['zoom', 'video', 'conferencing', 'meetings', 'webinar'],
  },
  {
    id: 'discord',
    title: 'Discord',
    icon: MessageCircle,
    description: 'Community platform scaling and real-time communication',
    path: '/solutions/discord',
    category: 'Communication',
    searchKeywords: ['discord', 'chat', 'community', 'gaming', 'voice'],
  },
  {
    id: 't-mobile-deutsche-telekom',
    title: 'T-Mobile / Deutsche Telekom',
    icon: Phone,
    description: '5G network deployment and legacy infrastructure',
    path: '/solutions/t-mobile-deutsche-telekom',
    category: 'Communication',
    searchKeywords: ['t-mobile', 'deutsche telekom', '5g', 'telecom'],
  },
  // Security
  {
    id: 'mcafee',
    title: 'McAfee',
    icon: ShieldCheck,
    description: 'Cybersecurity solutions and threat detection optimization',
    path: '/solutions/mcafee',
    category: 'Security',
    searchKeywords: ['mcafee', 'antivirus', 'security', 'cybersecurity', 'protection'],
  },
  // Government
  {
    id: 'fdic',
    title: 'FDIC',
    icon: Landmark,
    description: 'Deposit insurance, bank supervision, and regulatory compliance',
    path: '/solutions/fdic',
    category: 'Government',
    searchKeywords: ['fdic', 'insurance', 'banking', 'regulation', 'government'],
  },
  {
    id: 'brics',
    title: 'BRICS',
    icon: Globe,
    description: 'Cross-border payment coordination and currency exchange',
    path: '/solutions/brics',
    category: 'Government',
    searchKeywords: ['brics', 'international', 'payment', 'currency'],
  },
  {
    id: 'gbbc',
    title: 'GBBC',
    icon: Network,
    description: 'Global blockchain standards and industry collaboration',
    path: '/solutions/gbbc',
    category: 'Government',
    searchKeywords: ['gbbc', 'blockchain', 'standards', 'governance'],
  },
  {
    id: 'imf',
    title: 'IMF',
    icon: Landmark,
    description: 'Global economic surveillance and financial assistance',
    path: '/solutions/imf',
    category: 'Government',
    searchKeywords: ['imf', 'international', 'monetary', 'fund'],
  },
];
