/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgentConfig {
  'issueDate' : bigint,
  'status' : AgentStatus,
  'maxSessions' : [] | [bigint],
  'expiryTimestamp' : bigint,
  'approvalRequired' : boolean,
  'capabilities' : Array<string>,
  'name' : string,
  'roleDescription' : string,
  'policyScope' : string,
  'verificationStatus' : VerificationStatus,
  'maxBudget' : bigint,
}
export interface AgentDesignState {
  'name' : string,
  'roleDescription' : string,
}
export type AgentStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'suspended' : null };
export interface CommunityReply {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'topicId' : bigint,
}
export interface CommunityTopic {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'replyCount' : bigint,
}
export interface DebugRoleResult {
  'roleMapValue' : [] | [Role],
  'callerText' : string,
  'isAdmin' : boolean,
}
export interface EnterpriseOnboardingRequest {
  'id' : bigint,
  'contract' : string,
  'user' : Principal,
  'company' : string,
  'onboardingStatus' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'notes' : string,
  'timestamp' : Time,
}
export interface EvidenceItem {
  'id' : bigint,
  'owner' : Principal,
  'notarizationRecordId' : [] | [bigint],
  'description' : string,
  'timestamp' : bigint,
}
export type LabelSetState = { 'notFreezed' : null } |
  { 'freezed' : null };
export interface MarketplaceItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'price' : bigint,
}
export interface MarketplaceUnlock {
  'itemId' : bigint,
  'user' : Principal,
  'timestamp' : bigint,
}
export interface MetricsSummary {
  'startTime' : bigint,
  'totalTasks' : bigint,
  'completedTasks' : bigint,
  'endTime' : bigint,
  'agentId' : Principal,
  'complianceScore' : number,
  'pendingTasks' : bigint,
}
export interface NotarizationRecord {
  'id' : bigint,
  'contentHash' : [] | [Uint8Array],
  'contentText' : [] | [string],
  'owner' : Principal,
  'timestamp' : bigint,
}
export interface NotaryRequest { 'contentText' : string }
export interface PolicyRule {
  'ruleType' : string,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'enforced' : boolean,
  'scope' : string,
  'criteria' : [] | [string],
  'expiry' : [] | [bigint],
  'allowedActions' : Array<string>,
}
export interface RegistryEntry { 'content' : string, 'additions' : string }
export interface RewardEvent {
  'id' : bigint,
  'user' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'points' : bigint,
}
export interface RoadmapItem {
  'id' : bigint,
  'assignedTo' : Principal,
  'highPriority' : boolean,
  'description' : string,
  'lowPriority' : boolean,
  'category' : string,
}
export type Role = { 'admin' : null } |
  { 'user' : null };
export interface SharedAgentDesignState {
  'name' : string,
  'roleDescription' : string,
}
export type Time = bigint;
export interface TimeSeriesEntry {
  'completedTasks' : bigint,
  'timestamp' : bigint,
  'complianceScore' : number,
}
export interface TokenDistribution {
  'miningTokens' : bigint,
  'timeAiTokens' : bigint,
  'timeTokens' : bigint,
  'travAiTokens' : bigint,
  'travTokens' : bigint,
}
export type TokenOperation = {
    'trade' : {
      'to' : Principal,
      'from' : Principal,
      'timestamp' : bigint,
      'fromToken' : bigint,
      'amount' : bigint,
      'toToken' : bigint,
    }
  } |
  { 'burn' : { 'timestamp' : bigint, 'amount' : bigint } } |
  { 'mint' : { 'to' : Principal, 'timestamp' : bigint, 'amount' : bigint } } |
  {
    'transfer' : {
      'to' : Principal,
      'from' : Principal,
      'timestamp' : bigint,
      'amount' : bigint,
    }
  } |
  {
    'conversion' : {
      'to' : Principal,
      'from' : Principal,
      'timestamp' : bigint,
      'fromToken' : bigint,
      'amount' : bigint,
      'toToken' : bigint,
    }
  };
export interface Trade {
  'id' : bigint,
  'sellOrderId' : bigint,
  'buyOrderId' : bigint,
  'timestamp' : bigint,
  'tokenPair' : string,
  'price' : bigint,
  'amount' : bigint,
}
export interface TradeOrder {
  'id' : bigint,
  'status' : { 'cancelled' : null } |
    { 'open' : null } |
    { 'filled' : null },
  'user' : Principal,
  'orderType' : { 'buy' : null } |
    { 'sell' : null },
  'timestamp' : bigint,
  'tokenPair' : string,
  'price' : bigint,
  'amount' : bigint,
}
export interface UserProfile { 'name' : string }
export interface UserRoadmap {
  'highPriority' : Array<RoadmapItem>,
  'mediumPriority' : Array<RoadmapItem>,
  'lowPriority' : Array<RoadmapItem>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'unverified' : null } |
  { 'suspended' : null };
export interface WorkflowRun {
  'id' : bigint,
  'evidenceItemIds' : Array<bigint>,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'timestamp' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCommunityReply' : ActorMethod<[bigint, string], undefined>,
  'addRegistryEntry' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRoadmapItemToUser' : ActorMethod<[bigint, Principal], undefined>,
  'cancelTradeOrder' : ActorMethod<[bigint], undefined>,
  'createAgentDesign' : ActorMethod<[SharedAgentDesignState], undefined>,
  'createCommunityTopic' : ActorMethod<[string, string], bigint>,
  'createEvidenceItem' : ActorMethod<[string, [] | [bigint]], EvidenceItem>,
  'createMarketplaceItem' : ActorMethod<[MarketplaceItem], undefined>,
  'createPolicyRule' : ActorMethod<[PolicyRule], undefined>,
  'createRoadmapItem' : ActorMethod<[RoadmapItem], undefined>,
  'createUserRoadmap' : ActorMethod<
    [Array<RoadmapItem>, Array<RoadmapItem>, Array<RoadmapItem>],
    undefined
  >,
  'createWorkflowRun' : ActorMethod<
    [string, string, Array<bigint>],
    WorkflowRun
  >,
  'debugCaller' : ActorMethod<[], string>,
  'debugListUsers' : ActorMethod<[], Array<Principal>>,
  'debugRole' : ActorMethod<[], DebugRoleResult>,
  'deleteAgentDesign' : ActorMethod<[bigint], undefined>,
  'deleteMarketplaceItem' : ActorMethod<[bigint], undefined>,
  'deletePolicyRule' : ActorMethod<[bigint], undefined>,
  'deleteRoadmapItem' : ActorMethod<[bigint], undefined>,
  'earnRewardPoints' : ActorMethod<[bigint, string], undefined>,
  'ensureCallerUserExists' : ActorMethod<[], string>,
  'executeTrade' : ActorMethod<[bigint, bigint], undefined>,
  'forceAdmin' : ActorMethod<[], string>,
  'freezeLabelSet' : ActorMethod<[], undefined>,
  'getAgentDesigns' : ActorMethod<[], Array<AgentDesignState>>,
  'getAgentMetricsSummary' : ActorMethod<
    [Principal, bigint, bigint],
    MetricsSummary
  >,
  'getAgentTimeSeries' : ActorMethod<
    [Principal, bigint, bigint, bigint],
    Array<TimeSeriesEntry>
  >,
  'getAllAgentConfigs' : ActorMethod<[], Array<AgentConfig>>,
  'getAllEnterpriseOnboardingRequests' : ActorMethod<
    [],
    Array<EnterpriseOnboardingRequest>
  >,
  'getAllNotarizationRecords' : ActorMethod<[], Array<NotarizationRecord>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, Role]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityReplies' : ActorMethod<[bigint], Array<CommunityReply>>,
  'getCommunityTopic' : ActorMethod<[bigint], [] | [CommunityTopic]>,
  'getCommunityTopics' : ActorMethod<[], Array<CommunityTopic>>,
  'getComplianceLog' : ActorMethod<[boolean], Array<TokenOperation>>,
  'getCurrentUserRoadmap' : ActorMethod<[], UserRoadmap>,
  'getEnterpriseRequest' : ActorMethod<
    [bigint],
    [] | [EnterpriseOnboardingRequest]
  >,
  'getEvidenceItem' : ActorMethod<[bigint], [] | [EvidenceItem]>,
  'getEvidenceItems' : ActorMethod<[], Array<EvidenceItem>>,
  'getLabelSetState' : ActorMethod<[], LabelSetState>,
  'getMarketPrice' : ActorMethod<
    [boolean],
    { 'timestamp' : bigint, 'market' : bigint, 'priceUSDT' : bigint }
  >,
  'getMarketplaceItemById' : ActorMethod<[bigint], [] | [MarketplaceItem]>,
  'getMarketplaceItems' : ActorMethod<[], Array<MarketplaceItem>>,
  'getMyAgentConfigs' : ActorMethod<[], Array<AgentConfig>>,
  'getMyEnterpriseOnboardingRequests' : ActorMethod<
    [],
    Array<EnterpriseOnboardingRequest>
  >,
  'getMyMarketplaceUnlocks' : ActorMethod<[], Array<MarketplaceUnlock>>,
  'getMyNotarizationRecords' : ActorMethod<[], Array<NotarizationRecord>>,
  'getMyOpenOrders' : ActorMethod<[], Array<TradeOrder>>,
  'getMyRewardEvents' : ActorMethod<[], Array<RewardEvent>>,
  'getMyRewardPoints' : ActorMethod<[], bigint>,
  'getMyRoadmapItems' : ActorMethod<[], Array<RoadmapItem>>,
  'getMyRole' : ActorMethod<[], string>,
  'getMyUserExists' : ActorMethod<[], boolean>,
  'getPolicyRuleById' : ActorMethod<[bigint], [] | [PolicyRule]>,
  'getPolicyRules' : ActorMethod<[], Array<PolicyRule>>,
  'getRecentTrades' : ActorMethod<[], Array<Trade>>,
  'getRegistryEntries' : ActorMethod<[], Array<RegistryEntry>>,
  'getRoadmapItem' : ActorMethod<[bigint], RoadmapItem>,
  'getRoadmapItems' : ActorMethod<[], Array<RoadmapItem>>,
  'getRoadmapItemsForUser' : ActorMethod<[Principal], Array<RoadmapItem>>,
  'getSubscription' : ActorMethod<[Principal], string>,
  'getTokenBurnAnalysisMultiSeries' : ActorMethod<
    [boolean],
    Array<TokenOperation>
  >,
  'getTokenBurnAnalysisSingleSeries' : ActorMethod<
    [boolean],
    {
      'tokensMinted' : bigint,
      'tokensCirculating' : bigint,
      'revenueRetainedUSDT' : bigint,
      'tokensBurned' : bigint,
    }
  >,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRoadmap' : ActorMethod<[Principal], UserRoadmap>,
  'getWorkflowRun' : ActorMethod<[bigint], [] | [WorkflowRun]>,
  'getWorkflowRunEvidence' : ActorMethod<[bigint], Array<EvidenceItem>>,
  'getWorkflowRuns' : ActorMethod<[], Array<WorkflowRun>>,
  'initializeAdmin' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTokenDistributions' : ActorMethod<
    [boolean],
    {
      'timeTokenDistributions' : [] | [TokenDistribution],
      'travAiTokenDistributions' : [] | [TokenDistribution],
      'travTokenDistributions' : [] | [TokenDistribution],
      'timeAiTokenDistributions' : [] | [TokenDistribution],
      'miningTokenDistributions' : [] | [TokenDistribution],
    }
  >,
  'logTaskCompletion' : ActorMethod<[Principal, bigint, boolean], undefined>,
  'placeTradeOrder' : ActorMethod<
    [{ 'buy' : null } | { 'sell' : null }, string, bigint, bigint],
    bigint
  >,
  'redeemRewardPoints' : ActorMethod<[bigint, string], undefined>,
  'registerAgentConfig' : ActorMethod<[AgentConfig], undefined>,
  'registerSelf' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSubscription' : ActorMethod<[Principal, string], undefined>,
  'submitEnterpriseOnboardingRequest' : ActorMethod<[string, string], bigint>,
  'submitNotaryRequest' : ActorMethod<[NotaryRequest], NotarizationRecord>,
  'unlockMarketplaceItem' : ActorMethod<[bigint], undefined>,
  'updateAgentConfigs' : ActorMethod<[AgentConfig], undefined>,
  'updateAgentDesign' : ActorMethod<
    [bigint, SharedAgentDesignState],
    undefined
  >,
  'updateAgentStatus' : ActorMethod<[bigint, AgentStatus], undefined>,
  'updateAgentVerificationStatus' : ActorMethod<
    [Principal, bigint, VerificationStatus],
    undefined
  >,
  'updateEnterpriseRequestStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'approved' : null } |
        { 'rejected' : null },
      string,
    ],
    undefined
  >,
  'updateMarketplaceItem' : ActorMethod<[bigint, MarketplaceItem], undefined>,
  'updatePolicyRule' : ActorMethod<[bigint, PolicyRule], undefined>,
  'updateRoadmapItem' : ActorMethod<[bigint, RoadmapItem], undefined>,
  'verifyNotarizationHash' : ActorMethod<
    [Uint8Array],
    [] | [NotarizationRecord]
  >,
  'verifyNotarizationText' : ActorMethod<[string], [] | [NotarizationRecord]>,
  'whoami' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];