/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SharedAgentDesignState = IDL.Record({
  'name' : IDL.Text,
  'roleDescription' : IDL.Text,
});
export const EvidenceItem = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'notarizationRecordId' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MarketplaceItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const PolicyRule = IDL.Record({
  'ruleType' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'enforced' : IDL.Bool,
  'scope' : IDL.Text,
  'criteria' : IDL.Opt(IDL.Text),
  'expiry' : IDL.Opt(IDL.Int),
  'allowedActions' : IDL.Vec(IDL.Text),
});
export const RoadmapItem = IDL.Record({
  'id' : IDL.Nat,
  'assignedTo' : IDL.Principal,
  'highPriority' : IDL.Bool,
  'description' : IDL.Text,
  'lowPriority' : IDL.Bool,
  'category' : IDL.Text,
});
export const WorkflowRun = IDL.Record({
  'id' : IDL.Nat,
  'evidenceItemIds' : IDL.Vec(IDL.Nat),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const DebugRoleResult = IDL.Record({
  'roleMapValue' : IDL.Opt(Role),
  'callerText' : IDL.Text,
  'isAdmin' : IDL.Bool,
});
export const AgentDesignState = IDL.Record({
  'name' : IDL.Text,
  'roleDescription' : IDL.Text,
});
export const MetricsSummary = IDL.Record({
  'startTime' : IDL.Int,
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'endTime' : IDL.Int,
  'agentId' : IDL.Principal,
  'complianceScore' : IDL.Float64,
  'pendingTasks' : IDL.Nat,
});
export const TimeSeriesEntry = IDL.Record({
  'completedTasks' : IDL.Nat,
  'timestamp' : IDL.Int,
  'complianceScore' : IDL.Float64,
});
export const AgentStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'suspended' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'unverified' : IDL.Null,
  'suspended' : IDL.Null,
});
export const AgentConfig = IDL.Record({
  'issueDate' : IDL.Int,
  'status' : AgentStatus,
  'maxSessions' : IDL.Opt(IDL.Nat),
  'expiryTimestamp' : IDL.Int,
  'approvalRequired' : IDL.Bool,
  'capabilities' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'roleDescription' : IDL.Text,
  'policyScope' : IDL.Text,
  'verificationStatus' : VerificationStatus,
  'maxBudget' : IDL.Nat,
});
export const Time = IDL.Int;
export const EnterpriseOnboardingRequest = IDL.Record({
  'id' : IDL.Nat,
  'contract' : IDL.Text,
  'user' : IDL.Principal,
  'company' : IDL.Text,
  'onboardingStatus' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const NotarizationRecord = IDL.Record({
  'id' : IDL.Nat,
  'contentHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'contentText' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CommunityReply = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'topicId' : IDL.Nat,
});
export const CommunityTopic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'replyCount' : IDL.Nat,
});
export const TokenOperation = IDL.Variant({
  'trade' : IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'timestamp' : IDL.Int,
    'fromToken' : IDL.Nat,
    'amount' : IDL.Nat,
    'toToken' : IDL.Nat,
  }),
  'burn' : IDL.Record({ 'timestamp' : IDL.Int, 'amount' : IDL.Nat }),
  'mint' : IDL.Record({
    'to' : IDL.Principal,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  }),
  'transfer' : IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  }),
  'conversion' : IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'timestamp' : IDL.Int,
    'fromToken' : IDL.Nat,
    'amount' : IDL.Nat,
    'toToken' : IDL.Nat,
  }),
});
export const UserRoadmap = IDL.Record({
  'highPriority' : IDL.Vec(RoadmapItem),
  'mediumPriority' : IDL.Vec(RoadmapItem),
  'lowPriority' : IDL.Vec(RoadmapItem),
});
export const LabelSetState = IDL.Variant({
  'notFreezed' : IDL.Null,
  'freezed' : IDL.Null,
});
export const MarketplaceUnlock = IDL.Record({
  'itemId' : IDL.Nat,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const TradeOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'filled' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'orderType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'timestamp' : IDL.Int,
  'tokenPair' : IDL.Text,
  'price' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const RewardEvent = IDL.Record({
  'id' : IDL.Nat,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'points' : IDL.Int,
});
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'sellOrderId' : IDL.Nat,
  'buyOrderId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'tokenPair' : IDL.Text,
  'price' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const RegistryEntry = IDL.Record({
  'content' : IDL.Text,
  'additions' : IDL.Text,
});
export const TokenDistribution = IDL.Record({
  'miningTokens' : IDL.Nat,
  'timeAiTokens' : IDL.Nat,
  'timeTokens' : IDL.Nat,
  'travAiTokens' : IDL.Nat,
  'travTokens' : IDL.Nat,
});
export const NotaryRequest = IDL.Record({ 'contentText' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCommunityReply' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addRegistryEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRoadmapItemToUser' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'cancelTradeOrder' : IDL.Func([IDL.Nat], [], []),
  'createAgentDesign' : IDL.Func([SharedAgentDesignState], [], []),
  'createCommunityTopic' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createEvidenceItem' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [EvidenceItem],
      [],
    ),
  'createMarketplaceItem' : IDL.Func([MarketplaceItem], [], []),
  'createPolicyRule' : IDL.Func([PolicyRule], [], []),
  'createRoadmapItem' : IDL.Func([RoadmapItem], [], []),
  'createUserRoadmap' : IDL.Func(
      [IDL.Vec(RoadmapItem), IDL.Vec(RoadmapItem), IDL.Vec(RoadmapItem)],
      [],
      [],
    ),
  'createWorkflowRun' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [WorkflowRun],
      [],
    ),
  'debugCaller' : IDL.Func([], [IDL.Text], ['query']),
  'debugListUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'debugRole' : IDL.Func([], [DebugRoleResult], ['query']),
  'deleteAgentDesign' : IDL.Func([IDL.Nat], [], []),
  'deleteMarketplaceItem' : IDL.Func([IDL.Nat], [], []),
  'deletePolicyRule' : IDL.Func([IDL.Nat], [], []),
  'deleteRoadmapItem' : IDL.Func([IDL.Nat], [], []),
  'earnRewardPoints' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'ensureCallerUserExists' : IDL.Func([], [IDL.Text], []),
  'executeTrade' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'forceAdmin' : IDL.Func([], [IDL.Text], []),
  'freezeLabelSet' : IDL.Func([], [], []),
  'getAgentDesigns' : IDL.Func([], [IDL.Vec(AgentDesignState)], ['query']),
  'getAgentMetricsSummary' : IDL.Func(
      [IDL.Principal, IDL.Int, IDL.Int],
      [MetricsSummary],
      ['query'],
    ),
  'getAgentTimeSeries' : IDL.Func(
      [IDL.Principal, IDL.Int, IDL.Int, IDL.Int],
      [IDL.Vec(TimeSeriesEntry)],
      ['query'],
    ),
  'getAllAgentConfigs' : IDL.Func([], [IDL.Vec(AgentConfig)], ['query']),
  'getAllEnterpriseOnboardingRequests' : IDL.Func(
      [],
      [IDL.Vec(EnterpriseOnboardingRequest)],
      ['query'],
    ),
  'getAllNotarizationRecords' : IDL.Func(
      [],
      [IDL.Vec(NotarizationRecord)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Role))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityReplies' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CommunityReply)],
      ['query'],
    ),
  'getCommunityTopic' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CommunityTopic)],
      ['query'],
    ),
  'getCommunityTopics' : IDL.Func([], [IDL.Vec(CommunityTopic)], ['query']),
  'getComplianceLog' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(TokenOperation)],
      ['query'],
    ),
  'getCurrentUserRoadmap' : IDL.Func([], [UserRoadmap], ['query']),
  'getEnterpriseRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(EnterpriseOnboardingRequest)],
      ['query'],
    ),
  'getEvidenceItem' : IDL.Func([IDL.Nat], [IDL.Opt(EvidenceItem)], ['query']),
  'getEvidenceItems' : IDL.Func([], [IDL.Vec(EvidenceItem)], ['query']),
  'getLabelSetState' : IDL.Func([], [LabelSetState], ['query']),
  'getMarketPrice' : IDL.Func(
      [IDL.Bool],
      [
        IDL.Record({
          'timestamp' : IDL.Int,
          'market' : IDL.Int,
          'priceUSDT' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMarketplaceItemById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MarketplaceItem)],
      ['query'],
    ),
  'getMarketplaceItems' : IDL.Func([], [IDL.Vec(MarketplaceItem)], ['query']),
  'getMyAgentConfigs' : IDL.Func([], [IDL.Vec(AgentConfig)], ['query']),
  'getMyEnterpriseOnboardingRequests' : IDL.Func(
      [],
      [IDL.Vec(EnterpriseOnboardingRequest)],
      ['query'],
    ),
  'getMyMarketplaceUnlocks' : IDL.Func(
      [],
      [IDL.Vec(MarketplaceUnlock)],
      ['query'],
    ),
  'getMyNotarizationRecords' : IDL.Func(
      [],
      [IDL.Vec(NotarizationRecord)],
      ['query'],
    ),
  'getMyOpenOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
  'getMyRewardEvents' : IDL.Func([], [IDL.Vec(RewardEvent)], ['query']),
  'getMyRewardPoints' : IDL.Func([], [IDL.Int], ['query']),
  'getMyRoadmapItems' : IDL.Func([], [IDL.Vec(RoadmapItem)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Text], ['query']),
  'getMyUserExists' : IDL.Func([], [IDL.Bool], ['query']),
  'getPolicyRuleById' : IDL.Func([IDL.Nat], [IDL.Opt(PolicyRule)], ['query']),
  'getPolicyRules' : IDL.Func([], [IDL.Vec(PolicyRule)], ['query']),
  'getRecentTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getRegistryEntries' : IDL.Func([], [IDL.Vec(RegistryEntry)], ['query']),
  'getRoadmapItem' : IDL.Func([IDL.Nat], [RoadmapItem], ['query']),
  'getRoadmapItems' : IDL.Func([], [IDL.Vec(RoadmapItem)], ['query']),
  'getRoadmapItemsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(RoadmapItem)],
      ['query'],
    ),
  'getSubscription' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getTokenBurnAnalysisMultiSeries' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(TokenOperation)],
      ['query'],
    ),
  'getTokenBurnAnalysisSingleSeries' : IDL.Func(
      [IDL.Bool],
      [
        IDL.Record({
          'tokensMinted' : IDL.Nat,
          'tokensCirculating' : IDL.Nat,
          'revenueRetainedUSDT' : IDL.Nat,
          'tokensBurned' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRoadmap' : IDL.Func([IDL.Principal], [UserRoadmap], ['query']),
  'getWorkflowRun' : IDL.Func([IDL.Nat], [IDL.Opt(WorkflowRun)], ['query']),
  'getWorkflowRunEvidence' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EvidenceItem)],
      ['query'],
    ),
  'getWorkflowRuns' : IDL.Func([], [IDL.Vec(WorkflowRun)], ['query']),
  'initializeAdmin' : IDL.Func([], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTokenDistributions' : IDL.Func(
      [IDL.Bool],
      [
        IDL.Record({
          'timeTokenDistributions' : IDL.Opt(TokenDistribution),
          'travAiTokenDistributions' : IDL.Opt(TokenDistribution),
          'travTokenDistributions' : IDL.Opt(TokenDistribution),
          'timeAiTokenDistributions' : IDL.Opt(TokenDistribution),
          'miningTokenDistributions' : IDL.Opt(TokenDistribution),
        }),
      ],
      ['query'],
    ),
  'logTaskCompletion' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Bool], [], []),
  'placeTradeOrder' : IDL.Func(
      [
        IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'redeemRewardPoints' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'registerAgentConfig' : IDL.Func([AgentConfig], [], []),
  'registerSelf' : IDL.Func([], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSubscription' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'submitEnterpriseOnboardingRequest' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitNotaryRequest' : IDL.Func([NotaryRequest], [NotarizationRecord], []),
  'unlockMarketplaceItem' : IDL.Func([IDL.Nat], [], []),
  'updateAgentConfigs' : IDL.Func([AgentConfig], [], []),
  'updateAgentDesign' : IDL.Func([IDL.Nat, SharedAgentDesignState], [], []),
  'updateAgentStatus' : IDL.Func([IDL.Nat, AgentStatus], [], []),
  'updateAgentVerificationStatus' : IDL.Func(
      [IDL.Principal, IDL.Nat, VerificationStatus],
      [],
      [],
    ),
  'updateEnterpriseRequestStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateMarketplaceItem' : IDL.Func([IDL.Nat, MarketplaceItem], [], []),
  'updatePolicyRule' : IDL.Func([IDL.Nat, PolicyRule], [], []),
  'updateRoadmapItem' : IDL.Func([IDL.Nat, RoadmapItem], [], []),
  'verifyNotarizationHash' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(NotarizationRecord)],
      ['query'],
    ),
  'verifyNotarizationText' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(NotarizationRecord)],
      ['query'],
    ),
  'whoami' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SharedAgentDesignState = IDL.Record({
    'name' : IDL.Text,
    'roleDescription' : IDL.Text,
  });
  const EvidenceItem = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'notarizationRecordId' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MarketplaceItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PolicyRule = IDL.Record({
    'ruleType' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'enforced' : IDL.Bool,
    'scope' : IDL.Text,
    'criteria' : IDL.Opt(IDL.Text),
    'expiry' : IDL.Opt(IDL.Int),
    'allowedActions' : IDL.Vec(IDL.Text),
  });
  const RoadmapItem = IDL.Record({
    'id' : IDL.Nat,
    'assignedTo' : IDL.Principal,
    'highPriority' : IDL.Bool,
    'description' : IDL.Text,
    'lowPriority' : IDL.Bool,
    'category' : IDL.Text,
  });
  const WorkflowRun = IDL.Record({
    'id' : IDL.Nat,
    'evidenceItemIds' : IDL.Vec(IDL.Nat),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const DebugRoleResult = IDL.Record({
    'roleMapValue' : IDL.Opt(Role),
    'callerText' : IDL.Text,
    'isAdmin' : IDL.Bool,
  });
  const AgentDesignState = IDL.Record({
    'name' : IDL.Text,
    'roleDescription' : IDL.Text,
  });
  const MetricsSummary = IDL.Record({
    'startTime' : IDL.Int,
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'endTime' : IDL.Int,
    'agentId' : IDL.Principal,
    'complianceScore' : IDL.Float64,
    'pendingTasks' : IDL.Nat,
  });
  const TimeSeriesEntry = IDL.Record({
    'completedTasks' : IDL.Nat,
    'timestamp' : IDL.Int,
    'complianceScore' : IDL.Float64,
  });
  const AgentStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'unverified' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const AgentConfig = IDL.Record({
    'issueDate' : IDL.Int,
    'status' : AgentStatus,
    'maxSessions' : IDL.Opt(IDL.Nat),
    'expiryTimestamp' : IDL.Int,
    'approvalRequired' : IDL.Bool,
    'capabilities' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'roleDescription' : IDL.Text,
    'policyScope' : IDL.Text,
    'verificationStatus' : VerificationStatus,
    'maxBudget' : IDL.Nat,
  });
  const Time = IDL.Int;
  const EnterpriseOnboardingRequest = IDL.Record({
    'id' : IDL.Nat,
    'contract' : IDL.Text,
    'user' : IDL.Principal,
    'company' : IDL.Text,
    'onboardingStatus' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const NotarizationRecord = IDL.Record({
    'id' : IDL.Nat,
    'contentHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'contentText' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CommunityReply = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'topicId' : IDL.Nat,
  });
  const CommunityTopic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'replyCount' : IDL.Nat,
  });
  const TokenOperation = IDL.Variant({
    'trade' : IDL.Record({
      'to' : IDL.Principal,
      'from' : IDL.Principal,
      'timestamp' : IDL.Int,
      'fromToken' : IDL.Nat,
      'amount' : IDL.Nat,
      'toToken' : IDL.Nat,
    }),
    'burn' : IDL.Record({ 'timestamp' : IDL.Int, 'amount' : IDL.Nat }),
    'mint' : IDL.Record({
      'to' : IDL.Principal,
      'timestamp' : IDL.Int,
      'amount' : IDL.Nat,
    }),
    'transfer' : IDL.Record({
      'to' : IDL.Principal,
      'from' : IDL.Principal,
      'timestamp' : IDL.Int,
      'amount' : IDL.Nat,
    }),
    'conversion' : IDL.Record({
      'to' : IDL.Principal,
      'from' : IDL.Principal,
      'timestamp' : IDL.Int,
      'fromToken' : IDL.Nat,
      'amount' : IDL.Nat,
      'toToken' : IDL.Nat,
    }),
  });
  const UserRoadmap = IDL.Record({
    'highPriority' : IDL.Vec(RoadmapItem),
    'mediumPriority' : IDL.Vec(RoadmapItem),
    'lowPriority' : IDL.Vec(RoadmapItem),
  });
  const LabelSetState = IDL.Variant({
    'notFreezed' : IDL.Null,
    'freezed' : IDL.Null,
  });
  const MarketplaceUnlock = IDL.Record({
    'itemId' : IDL.Nat,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const TradeOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'open' : IDL.Null,
      'filled' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'orderType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'timestamp' : IDL.Int,
    'tokenPair' : IDL.Text,
    'price' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const RewardEvent = IDL.Record({
    'id' : IDL.Nat,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'points' : IDL.Int,
  });
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'sellOrderId' : IDL.Nat,
    'buyOrderId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'tokenPair' : IDL.Text,
    'price' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const RegistryEntry = IDL.Record({
    'content' : IDL.Text,
    'additions' : IDL.Text,
  });
  const TokenDistribution = IDL.Record({
    'miningTokens' : IDL.Nat,
    'timeAiTokens' : IDL.Nat,
    'timeTokens' : IDL.Nat,
    'travAiTokens' : IDL.Nat,
    'travTokens' : IDL.Nat,
  });
  const NotaryRequest = IDL.Record({ 'contentText' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCommunityReply' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addRegistryEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRoadmapItemToUser' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'cancelTradeOrder' : IDL.Func([IDL.Nat], [], []),
    'createAgentDesign' : IDL.Func([SharedAgentDesignState], [], []),
    'createCommunityTopic' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createEvidenceItem' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [EvidenceItem],
        [],
      ),
    'createMarketplaceItem' : IDL.Func([MarketplaceItem], [], []),
    'createPolicyRule' : IDL.Func([PolicyRule], [], []),
    'createRoadmapItem' : IDL.Func([RoadmapItem], [], []),
    'createUserRoadmap' : IDL.Func(
        [IDL.Vec(RoadmapItem), IDL.Vec(RoadmapItem), IDL.Vec(RoadmapItem)],
        [],
        [],
      ),
    'createWorkflowRun' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [WorkflowRun],
        [],
      ),
    'debugCaller' : IDL.Func([], [IDL.Text], ['query']),
    'debugListUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'debugRole' : IDL.Func([], [DebugRoleResult], ['query']),
    'deleteAgentDesign' : IDL.Func([IDL.Nat], [], []),
    'deleteMarketplaceItem' : IDL.Func([IDL.Nat], [], []),
    'deletePolicyRule' : IDL.Func([IDL.Nat], [], []),
    'deleteRoadmapItem' : IDL.Func([IDL.Nat], [], []),
    'earnRewardPoints' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'ensureCallerUserExists' : IDL.Func([], [IDL.Text], []),
    'executeTrade' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'forceAdmin' : IDL.Func([], [IDL.Text], []),
    'freezeLabelSet' : IDL.Func([], [], []),
    'getAgentDesigns' : IDL.Func([], [IDL.Vec(AgentDesignState)], ['query']),
    'getAgentMetricsSummary' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Int],
        [MetricsSummary],
        ['query'],
      ),
    'getAgentTimeSeries' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Int, IDL.Int],
        [IDL.Vec(TimeSeriesEntry)],
        ['query'],
      ),
    'getAllAgentConfigs' : IDL.Func([], [IDL.Vec(AgentConfig)], ['query']),
    'getAllEnterpriseOnboardingRequests' : IDL.Func(
        [],
        [IDL.Vec(EnterpriseOnboardingRequest)],
        ['query'],
      ),
    'getAllNotarizationRecords' : IDL.Func(
        [],
        [IDL.Vec(NotarizationRecord)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Role))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityReplies' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CommunityReply)],
        ['query'],
      ),
    'getCommunityTopic' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CommunityTopic)],
        ['query'],
      ),
    'getCommunityTopics' : IDL.Func([], [IDL.Vec(CommunityTopic)], ['query']),
    'getComplianceLog' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(TokenOperation)],
        ['query'],
      ),
    'getCurrentUserRoadmap' : IDL.Func([], [UserRoadmap], ['query']),
    'getEnterpriseRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(EnterpriseOnboardingRequest)],
        ['query'],
      ),
    'getEvidenceItem' : IDL.Func([IDL.Nat], [IDL.Opt(EvidenceItem)], ['query']),
    'getEvidenceItems' : IDL.Func([], [IDL.Vec(EvidenceItem)], ['query']),
    'getLabelSetState' : IDL.Func([], [LabelSetState], ['query']),
    'getMarketPrice' : IDL.Func(
        [IDL.Bool],
        [
          IDL.Record({
            'timestamp' : IDL.Int,
            'market' : IDL.Int,
            'priceUSDT' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMarketplaceItemById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MarketplaceItem)],
        ['query'],
      ),
    'getMarketplaceItems' : IDL.Func([], [IDL.Vec(MarketplaceItem)], ['query']),
    'getMyAgentConfigs' : IDL.Func([], [IDL.Vec(AgentConfig)], ['query']),
    'getMyEnterpriseOnboardingRequests' : IDL.Func(
        [],
        [IDL.Vec(EnterpriseOnboardingRequest)],
        ['query'],
      ),
    'getMyMarketplaceUnlocks' : IDL.Func(
        [],
        [IDL.Vec(MarketplaceUnlock)],
        ['query'],
      ),
    'getMyNotarizationRecords' : IDL.Func(
        [],
        [IDL.Vec(NotarizationRecord)],
        ['query'],
      ),
    'getMyOpenOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
    'getMyRewardEvents' : IDL.Func([], [IDL.Vec(RewardEvent)], ['query']),
    'getMyRewardPoints' : IDL.Func([], [IDL.Int], ['query']),
    'getMyRoadmapItems' : IDL.Func([], [IDL.Vec(RoadmapItem)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Text], ['query']),
    'getMyUserExists' : IDL.Func([], [IDL.Bool], ['query']),
    'getPolicyRuleById' : IDL.Func([IDL.Nat], [IDL.Opt(PolicyRule)], ['query']),
    'getPolicyRules' : IDL.Func([], [IDL.Vec(PolicyRule)], ['query']),
    'getRecentTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getRegistryEntries' : IDL.Func([], [IDL.Vec(RegistryEntry)], ['query']),
    'getRoadmapItem' : IDL.Func([IDL.Nat], [RoadmapItem], ['query']),
    'getRoadmapItems' : IDL.Func([], [IDL.Vec(RoadmapItem)], ['query']),
    'getRoadmapItemsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(RoadmapItem)],
        ['query'],
      ),
    'getSubscription' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getTokenBurnAnalysisMultiSeries' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(TokenOperation)],
        ['query'],
      ),
    'getTokenBurnAnalysisSingleSeries' : IDL.Func(
        [IDL.Bool],
        [
          IDL.Record({
            'tokensMinted' : IDL.Nat,
            'tokensCirculating' : IDL.Nat,
            'revenueRetainedUSDT' : IDL.Nat,
            'tokensBurned' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRoadmap' : IDL.Func([IDL.Principal], [UserRoadmap], ['query']),
    'getWorkflowRun' : IDL.Func([IDL.Nat], [IDL.Opt(WorkflowRun)], ['query']),
    'getWorkflowRunEvidence' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EvidenceItem)],
        ['query'],
      ),
    'getWorkflowRuns' : IDL.Func([], [IDL.Vec(WorkflowRun)], ['query']),
    'initializeAdmin' : IDL.Func([], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTokenDistributions' : IDL.Func(
        [IDL.Bool],
        [
          IDL.Record({
            'timeTokenDistributions' : IDL.Opt(TokenDistribution),
            'travAiTokenDistributions' : IDL.Opt(TokenDistribution),
            'travTokenDistributions' : IDL.Opt(TokenDistribution),
            'timeAiTokenDistributions' : IDL.Opt(TokenDistribution),
            'miningTokenDistributions' : IDL.Opt(TokenDistribution),
          }),
        ],
        ['query'],
      ),
    'logTaskCompletion' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Bool], [], []),
    'placeTradeOrder' : IDL.Func(
        [
          IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'redeemRewardPoints' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'registerAgentConfig' : IDL.Func([AgentConfig], [], []),
    'registerSelf' : IDL.Func([], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSubscription' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'submitEnterpriseOnboardingRequest' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitNotaryRequest' : IDL.Func([NotaryRequest], [NotarizationRecord], []),
    'unlockMarketplaceItem' : IDL.Func([IDL.Nat], [], []),
    'updateAgentConfigs' : IDL.Func([AgentConfig], [], []),
    'updateAgentDesign' : IDL.Func([IDL.Nat, SharedAgentDesignState], [], []),
    'updateAgentStatus' : IDL.Func([IDL.Nat, AgentStatus], [], []),
    'updateAgentVerificationStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat, VerificationStatus],
        [],
        [],
      ),
    'updateEnterpriseRequestStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateMarketplaceItem' : IDL.Func([IDL.Nat, MarketplaceItem], [], []),
    'updatePolicyRule' : IDL.Func([IDL.Nat, PolicyRule], [], []),
    'updateRoadmapItem' : IDL.Func([IDL.Nat, RoadmapItem], [], []),
    'verifyNotarizationHash' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(NotarizationRecord)],
        ['query'],
      ),
    'verifyNotarizationText' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(NotarizationRecord)],
        ['query'],
      ),
    'whoami' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };